dataset_params:
  # Path to data
  root_dir: /
  frame_shape: [112, 112, 112]
  pairs_list: *.csv
  # data name
  object: cardiac
  # Augmentation parameters see augmentation.py for all posible augmentations
  augmentation_params:
    flip_param:
      horizontal_flip: True
      time_flip: True
    jitter_param:
      brightness: 0.1
      contrast: 0.1
      saturation: 0.1
      hue: 0.1

# Defines model architecture
model_params:
  common_params:
    # Number of landmark
    motion_num_kp: 24
    still_num_kp: 0
    # Number of channels per image
    num_channels: 1
    # Using first or zero order model
    estimate_jacobian: False
  kp_detector_params:
     # Softmax temperature for landmark heatmaps
     temperature: 0.2
     # Number of features mutliplier
     block_expansion: 32
     # Maximum allowed number of features
     max_features: 1024
     # Number of block in Unet. Can be increased or decreased depending or resolution.
     num_blocks: 5
     scale_factor: [7,10]
  generator_params:
    # Number of features mutliplier
    block_expansion: 32
    # Maximum allowed number of features
    max_features: 512
    # Number of downsampling blocks in Jonson architecture.
    # Can be increased or decreased depending or resolution.
    num_down_blocks: 2
    # Number of ResBlocks  in Jonson architecture.
    num_bottleneck_blocks: 2
    # Use occlusion map or not
    estimate_occlusion_map: False

    dense_motion_params:
      # Number of features mutliplier
      block_expansion: 32
      # Maximum allowed number of features
      max_features: 1024
      # Number of block in Unet. Can be increased or decreased depending or resolution.
      num_blocks: 5
      scale_factor: [6,10]
      kp_variance: 0.006
  discriminator_params:
    # Discriminator can be multiscale, if you want 2 discriminator on original
    # resolution and half of the original, specify scales: [1, 0.5]
    scales: [0.6]
    # Number of features mutliplier
    block_expansion: 16
    # Maximum allowed number of features
    max_features: 512
    # Number of blocks. Can be increased or decreased depending or resolution.
    num_blocks: 4

# Parameters of training
train_params:
  # Number of training epochs 
  num_epochs: 200
  # For better i/o performance when number of videos is small number of epochs can be multiplied by this number.
  # Thus effectivlly with num_repeats=100 each epoch is 100 times larger. 
  num_repeats: 150
  # Drop learning rate by 10 times after this epochs 
  epoch_milestones: [80, 120]
  # Initial learing rate for all modules
  lr_generator: 2.0e-5
  lr_discriminator: 4.0e-5
  lr_kp_detector: 6.0e-5
  batch_size: 1
  # Scales for perceptual pyramide loss. If scales = [1, 0.5, 0.25, 0.125] and image resolution is 256x256,
  # than the loss will be computer on resolutions 256x256, 128x128, 64x64, 32x32.
  scales: [1, 0.5]
  # Save checkpoint this frequently. If checkpoint_freq=50, checkpoint will be saved every 50 epochs.
  checkpoint_freq: 5
  # Parameters of transform for equivariance loss
  transform_params:
    # Sigma for affine part
    sigma_affine: 0.04
    # Sigma for deformation part
    sigma_tps: 0.0008
    # Number of point in the deformation grid
    points_tps: 3
  augmentation_params:
    # Sigma for affine part
    sigma_affine: 0.05
    # Sigma for deformation part
    sigma_tps: 0.0006
    # Number of point in the deformation grid
    points_tps: 3
  loss_weights:
    # Weight for LSGAN loss in generator, 0 for no adversarial loss.
    generator_gan: 0
    pointdisc_gan: 0
    tps: [4, 4]
    # Weight for LSGAN loss in discriminator
    discriminator_gan: 1
    # Weights for feature matching loss, the number should be the same as number of blocks in discriminator.
    feature_matching: [10, 10, 10, 10]
    # Weights for perceptual loss.
    perceptual: [100, 10]
    # Weights for value equivariance.
    deformed: [400, 400]
    equivariance_value: 100 
    union: 0.4
    still: 400
    kp_sum_value: 1

# Parameters of reconstruction
reconstruction_params:
  num_frames: 5
  # Format for visualization.
  format: ''

# Parameters of animation
animate_params:
  # Maximum number of pairs for animation, the pairs will be either taken from pairs_list or random.
  num_pairs: 50
  lr: 6.0e-5
  # Format for visualization
  format: ''
  # Normalization of diriving keypoints
  normalization_params:
    # Increase or decrease relative movement scale depending on the size of the object
    adapt_movement_scale: False
    # Apply only relative displacement of the keypoint
    use_relative_movement: True
    # Apply only relative change in jacobian
    use_relative_jacobian: True
  transform_params:
    # Sigma for affine part
    sigma_affine: 0.08
    # Sigma for deformation part
    sigma_tps: 0.0008
    # Number of point in the deformation grid
    points_tps: 3

# Visualization parameters
visualizer_params:
  # Draw keypoints of this size, increase or decrease depending on resolution
  kp_size: 5
  # Draw white border around images
  draw_border: True
  # Color map for keypoints
  colormap: 'gist_rainbow'
